import { SQLiteDatabase } from "expo-sqlite";
import { mapDBToTask, mapTaskToDB } from "./dbUtils";
import { formatISO } from 'date-fns';


// Add a Todo
export const addTodo = async (db: SQLiteDatabase, task: string): Promise<void> => {
    const taskObj = {
        id: 0,  // Assuming ID is auto-generated by the database
        task: task,
        done: false,
        createdAt: new Date(),
        dueAt: null,
        completedAt: null,
        isDeleted: false,
        deletedAt: null,
        isTask: false,
    };

    const statement = await db.prepareAsync(
        `INSERT INTO todos (task, done, created_at, is_deleted, is_task)
        VALUES ($task, $done, $createdAt, $isDeleted, $isTask)`
    );
    
    const taskToInsert = mapTaskToDB(taskObj);  // Convert the task object to a database row

    try {
        await statement.executeAsync({
            $task: taskToInsert.task,
            $done: taskToInsert.done,
            $createdAt: taskToInsert.created_at,
            $isDeleted: taskToInsert.is_deleted,
            $isTask: taskToInsert.is_task,
        });
    } finally {
        await statement.finalizeAsync();
    }
};

// Get Todos
export const getTodos = async (db: SQLiteDatabase) => {
    const statement = await db.prepareAsync(`SELECT * FROM todos WHERE is_deleted = 0 AND is_task = 0`);
    try {
        const result = await statement.executeAsync();
        const rows = await result.getAllAsync();
        return rows.map(mapDBToTask);  // Map each database row to a Task object
    } finally {
        await statement.finalizeAsync();
    }
};

// Delete Todo
export const deleteTodo = async (db: SQLiteDatabase, id: number): Promise<void> => {
    const statement = await db.prepareAsync(
        `UPDATE todos SET is_deleted = 1, deleted_at = $deletedAt WHERE id = $id`
    );
    try {
        await statement.executeAsync({
            $deletedAt: formatISO(new Date()),
            $id: id,
        });
    } finally {
        await statement.finalizeAsync();
    }
};

// Complete Todo
export const completeTodo = async (db: SQLiteDatabase, id: number): Promise<void> => {
    const statement = await db.prepareAsync(
        `UPDATE todos SET done = 1, completed_at = $completedAt WHERE id = $id`
    );
    try {
        await statement.executeAsync({
            $completedAt: formatISO(new Date()),
            $id: id,
        });
    } finally {
        await statement.finalizeAsync();
    }
};

// Uncomplete Todo
export const uncompleteTodo = async (db: SQLiteDatabase, id: number): Promise<void> => {
    const statement = await db.prepareAsync(
        `UPDATE todos SET done = 0, completed_at = NULL WHERE id = $id`
    );
    try {
        await statement.executeAsync({ $id: id });
    } finally {
        await statement.finalizeAsync();
    }
};




// Add a Task
export const addTask = async (db: SQLiteDatabase, task: string): Promise<void> => {
    const statement = await db.prepareAsync(
        `INSERT INTO todos (task, done, created_at, is_deleted, is_task)
        VALUES ($task, $done, $createdAt, $isDeleted, $isTask)`
    );
    try {
        await statement.executeAsync({
            $task: task,
            $done: 0, // false
            $createdAt: formatISO(new Date()),
            $isDeleted: 0, // false
            $isTask: 1, // true (indicates a task)
        });
    } finally {
        await statement.finalizeAsync();
    }
};

// Get Tasks
export const getTasks = async (db: SQLiteDatabase) => {
    const statement = await db.prepareAsync(`SELECT * FROM todos WHERE is_deleted = 0 AND is_task = 1`);
    try {
        const result = await statement.executeAsync();
        return await result.getAllAsync();
    } finally {
        await statement.finalizeAsync();
    }
};

// Delete Task
export const deleteTask = async (db: SQLiteDatabase, id: number): Promise<void> => {
    const statement = await db.prepareAsync(
        `UPDATE todos SET is_deleted = 1, deleted_at = $deletedAt WHERE id = $id`
    );
    try {
        await statement.executeAsync({
            $deletedAt: formatISO(new Date()),
            $id: id,
        });
    } finally {
        await statement.finalizeAsync();
    }
};

// Complete Task
export const completeTask = async (db: SQLiteDatabase, id: number): Promise<void> => {
    const statement = await db.prepareAsync(
        `UPDATE todos SET done = 1, completed_at = $completedAt WHERE id = $id`
    );
    try {
        await statement.executeAsync({
            $completedAt: formatISO(new Date()),
            $id: id,
        });
    } finally {
        await statement.finalizeAsync();
    }
};

// Uncomplete Task
export const uncompleteTask = async (db: SQLiteDatabase, id: number): Promise<void> => {
    const statement = await db.prepareAsync(
        `UPDATE todos SET done = 0, completed_at = NULL WHERE id = $id`
    );
    try {
        await statement.executeAsync({ $id: id });
    } finally {
        await statement.finalizeAsync();
    }
};
